/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ocac_Lab_Equipment_System;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class ocacLab6 extends javax.swing.JFrame {

    /**
     * Creates new form ocacLab1
     */
       public int newComputer =0;
       public  int newChair = 0;
       public int newLight =0;
       public int newAc=0;
       
        public int removenewComputer =0;
       public  int removenewChair = 0;
       public int removenewLight =0;
       public int removenewAc=0;
       
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public String ctrGetData,chiarGetData,lightGetData,acGetData ="";
    public ocacLab6() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Initial Hide of Updated Values
        aUp1.setVisible(false);
        aUp2.setVisible(false);
        aUp3.setVisible(false);
        aUp4.setVisible(false);
        addSubmit.setVisible(false);
        upLabel.setVisible(false);
        
        //Initial hide of Remove Updated Values
        rUp1.setVisible(false);
        rUp2.setVisible(false);
        rUp3.setVisible(false);
        rUp4.setVisible(false);
        removeSubmit.setVisible(false);
          upLabel1.setVisible(false);
      cancelAdding.setVisible(false);
      cancelRemove.setVisible(false);
        
        
        
          try{  //Creating Connection to Data Base
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    String url = "jdbc:oracle:thin:@//localhost:1521/XE";
                    String user = "system";
                   con = DriverManager.getConnection(url, user, "root");
                 String labId="lab1";
                  pst=con.prepareStatement("select computers,chairs,lights,ac from ocacLab6 where labid=?");
                    pst.setString(1,labId);
                   rs=pst.executeQuery();
                    while(rs.next()){
                        ctrGetData = String.valueOf(rs.getInt(1));
                        chiarGetData = String.valueOf(rs.getInt(2));
                        lightGetData =String.valueOf(rs.getInt(3));
                        acGetData=String.valueOf(rs.getInt(4));
                    }
                    computerView.setEditable(false);
                    chairView.setEditable(false);
                    lightView.setEditable(false);
                     acView.setEditable(false);
                   computerView.setText(ctrGetData);
                   chairView.setText(chiarGetData);
                   acView.setText(acGetData);
                    lightView.setText(lightGetData);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, e);
                }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        next1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        labTabPan = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        computerView = new javax.swing.JTextField();
        chairView = new javax.swing.JTextField();
        lightView = new javax.swing.JTextField();
        acView = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        computerAdding = new javax.swing.JTextField();
        lightAdding = new javax.swing.JTextField();
        chairAdding = new javax.swing.JTextField();
        acAdding = new javax.swing.JTextField();
        aUp1 = new javax.swing.JLabel();
        aUp2 = new javax.swing.JLabel();
        aUp4 = new javax.swing.JLabel();
        aUp3 = new javax.swing.JLabel();
        upLabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        addSubmit = new javax.swing.JButton();
        cancelAdding = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        computerRemove = new javax.swing.JTextField();
        lightRemove = new javax.swing.JTextField();
        chairRemove = new javax.swing.JTextField();
        acRemove = new javax.swing.JTextField();
        rUp1 = new javax.swing.JLabel();
        rUp2 = new javax.swing.JLabel();
        rUp4 = new javax.swing.JLabel();
        rUp3 = new javax.swing.JLabel();
        upLabel1 = new javax.swing.JLabel();
        push2 = new javax.swing.JButton();
        removeSubmit = new javax.swing.JButton();
        cancelRemove = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin View");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Home");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Add");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Remove");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("Exit");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        next1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        next1.setText("<");
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(next1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(jButton2)
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addGap(55, 55, 55)
                .addComponent(jButton4)
                .addGap(42, 42, 42)
                .addComponent(next1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Lab 6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 167, 470));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("Summary");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setText("Computers");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setText("Chairs");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setText("Lights");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setText("Air Conditioner");

        computerView.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        computerView.setForeground(new java.awt.Color(204, 0, 0));
        computerView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerViewActionPerformed(evt);
            }
        });

        chairView.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        chairView.setForeground(new java.awt.Color(204, 0, 0));
        chairView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chairViewActionPerformed(evt);
            }
        });

        lightView.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lightView.setForeground(new java.awt.Color(204, 0, 0));
        lightView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightViewActionPerformed(evt);
            }
        });

        acView.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        acView.setForeground(new java.awt.Color(204, 0, 0));
        acView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acViewActionPerformed(evt);
            }
        });

        refresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acView, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(lightView, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chairView, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(computerView, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(159, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(refresh)
                        .addGap(203, 203, 203))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(computerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chairView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(refresh)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        labTabPan.addTab("HOME", jPanel1);

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Add Computers");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Add Lights");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Add Chairs");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Add AC");

        computerAdding.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        computerAdding.setForeground(new java.awt.Color(204, 0, 0));
        computerAdding.setText("0");
        computerAdding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerAddingActionPerformed(evt);
            }
        });

        lightAdding.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lightAdding.setForeground(new java.awt.Color(204, 0, 0));
        lightAdding.setText("0");
        lightAdding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightAddingActionPerformed(evt);
            }
        });

        chairAdding.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        chairAdding.setForeground(new java.awt.Color(204, 0, 0));
        chairAdding.setText("0");
        chairAdding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chairAddingActionPerformed(evt);
            }
        });

        acAdding.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        acAdding.setForeground(new java.awt.Color(204, 0, 0));
        acAdding.setText("0");
        acAdding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acAddingActionPerformed(evt);
            }
        });

        aUp1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aUp1.setForeground(new java.awt.Color(153, 0, 0));
        aUp1.setText("00");

        aUp2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aUp2.setForeground(new java.awt.Color(153, 0, 0));
        aUp2.setText("00");

        aUp4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aUp4.setForeground(new java.awt.Color(153, 0, 0));
        aUp4.setText("00");

        aUp3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aUp3.setForeground(new java.awt.Color(153, 0, 0));
        aUp3.setText("00");

        upLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        upLabel.setText("Updated Value");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Push");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        addSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSubmit.setText("Submit");
        addSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubmitActionPerformed(evt);
            }
        });

        cancelAdding.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelAdding.setText("Cancel Adding");
        cancelAdding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton5)
                        .addGap(88, 88, 88)
                        .addComponent(addSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(upLabel)))
                .addGap(79, 79, 79))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(computerAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lightAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chairAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aUp2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aUp3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aUp4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(upLabel)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(computerAdding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aUp1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lightAdding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aUp2)))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chairAdding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aUp3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acAdding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aUp4))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(addSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(cancelAdding)
                .addGap(25, 25, 25))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADD COMPONENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        labTabPan.addTab("ADD", jPanel3);

        jPanel9.setBackground(new java.awt.Color(0, 0, 204));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Add Computers");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Add Lights");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("Add Chairs");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Add AC");

        computerRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        computerRemove.setForeground(new java.awt.Color(204, 0, 0));
        computerRemove.setText("0");
        computerRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerRemoveActionPerformed(evt);
            }
        });

        lightRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lightRemove.setForeground(new java.awt.Color(204, 0, 0));
        lightRemove.setText("0");
        lightRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightRemoveActionPerformed(evt);
            }
        });

        chairRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        chairRemove.setForeground(new java.awt.Color(204, 0, 0));
        chairRemove.setText("0");
        chairRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chairRemoveActionPerformed(evt);
            }
        });

        acRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        acRemove.setForeground(new java.awt.Color(204, 0, 0));
        acRemove.setText("0");
        acRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acRemoveActionPerformed(evt);
            }
        });

        rUp1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rUp1.setForeground(new java.awt.Color(153, 0, 0));
        rUp1.setText("0");

        rUp2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rUp2.setForeground(new java.awt.Color(153, 0, 0));
        rUp2.setText("0");

        rUp4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rUp4.setForeground(new java.awt.Color(153, 0, 0));
        rUp4.setText("0");

        rUp3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rUp3.setForeground(new java.awt.Color(153, 0, 0));
        rUp3.setText("0");

        upLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        upLabel1.setText("Updated Value");

        push2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        push2.setText("Push");
        push2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                push2ActionPerformed(evt);
            }
        });

        removeSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeSubmit.setText("Submit");
        removeSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSubmitActionPerformed(evt);
            }
        });

        cancelRemove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelRemove.setText("Cancel Removing");
        cancelRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(computerRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lightRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chairRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rUp2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rUp3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rUp4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(push2)
                        .addGap(86, 86, 86)
                        .addComponent(removeSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(upLabel1)))
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelRemove)
                .addGap(160, 160, 160))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(upLabel1)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(computerRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rUp1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lightRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rUp2)))
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chairRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rUp3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rUp4))
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(push2)
                    .addComponent(removeSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(cancelRemove)
                .addGap(27, 27, 27))
        );

        jLabel35.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("REMOVE COMPONENT");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        labTabPan.addTab("REMOVE", jPanel9);

        getContentPane().add(labTabPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, -35, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       labTabPan.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        labTabPan.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        labTabPan.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void acViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acViewActionPerformed

    private void lightViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightViewActionPerformed

    private void chairViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chairViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chairViewActionPerformed

    private void computerViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerViewActionPerformed

    private void computerAddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerAddingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerAddingActionPerformed

    private void lightAddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightAddingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightAddingActionPerformed

    private void chairAddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chairAddingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chairAddingActionPerformed

    private void acAddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acAddingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acAddingActionPerformed

    private void computerRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerRemoveActionPerformed

    private void lightRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightRemoveActionPerformed

    private void chairRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chairRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chairRemoveActionPerformed

    private void acRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acRemoveActionPerformed

    private void push2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_push2ActionPerformed
       
        
        
         int oldComputer1 = Integer.parseInt(computerRemove.getText());
     int oldChair1 = Integer.parseInt(chairRemove.getText());
        int oldLight1 = Integer.parseInt(lightRemove.getText());
      int oldAc1=Integer.parseInt(acRemove.getText());
      
        
        try{  //Creating Connection to Data Base
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    String url = "jdbc:oracle:thin:@//localhost:1521/XE";
                    String user = "system";
                   con = DriverManager.getConnection(url, user, "root");
                 String labId="lab1";
                  pst=con.prepareStatement("select computers,lights,chairs,ac from ocacLab6 where labid=?");
                    pst.setString(1,labId);
                   rs=pst.executeQuery();
                    while(rs.next()){
                       removenewComputer= rs.getInt(1)-oldComputer1;
                        removenewLight=rs.getInt(2)-oldLight1;
                       removenewChair = rs.getInt(1)-oldChair1;
                        removenewAc=rs.getInt(1)-oldAc1;
                    }
                    
                    
                    rUp1.setText(String.valueOf(removenewComputer));
                    rUp2.setText(String.valueOf(removenewLight));
                    rUp3.setText(String.valueOf(removenewChair));
                    rUp4.setText(String.valueOf(removenewAc));
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, e);
                } 
        
        
        
        rUp1.setVisible(true);
        rUp2.setVisible(true);
        rUp3.setVisible(true);
        rUp4.setVisible(true);
        removeSubmit.setVisible(true);
        upLabel1.setVisible(true);
        cancelRemove.setVisible(true);
        
        
        
         
        
        
        
    }//GEN-LAST:event_push2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      int oldComputer = Integer.parseInt(computerAdding.getText());
     int oldChair = Integer.parseInt(chairAdding.getText());
        int oldLight = Integer.parseInt(lightAdding.getText());
      int oldAc=Integer.parseInt(acAdding.getText());
      
        
        try{  //Creating Connection to Data Base
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    String url = "jdbc:oracle:thin:@//localhost:1521/XE";
                    String user = "system";
                   con = DriverManager.getConnection(url, user, "root");
                 String labId="lab1";
                  pst=con.prepareStatement("select computers,lights,chairs,ac from ocacLab6 where labid=?");
                    pst.setString(1,labId);
                   rs=pst.executeQuery();
                    while(rs.next()){
                       newComputer= rs.getInt(1)+oldComputer;
                        newLight=rs.getInt(2)+oldLight;
                       newChair = rs.getInt(1)+oldChair;
                        newAc=rs.getInt(1)+oldAc;
                    }
                    
                    
                    aUp1.setText(String.valueOf(newComputer));
                    aUp2.setText(String.valueOf(newLight));
                    aUp3.setText(String.valueOf(newChair));
                    aUp4.setText(String.valueOf(newAc));
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, e);
                } 
        
        
        
        
        aUp1.setVisible(true);
        aUp2.setVisible(true);
        aUp3.setVisible(true);
        aUp4.setVisible(true);
        addSubmit.setVisible(true);
        upLabel.setVisible(true);
        cancelAdding.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cancelAddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddingActionPerformed
        
        aUp1.setVisible(false);
        aUp2.setVisible(false);
        aUp3.setVisible(false);
        aUp4.setVisible(false);
        addSubmit.setVisible(false);
        upLabel.setVisible(false);
        
        computerAdding.setText("0");
        computerAdding.setText("0");
        computerAdding.setText("0");
        computerAdding.setText("0");
        computerAdding.setText("0");
        
        cancelAdding.setVisible(false);
    }//GEN-LAST:event_cancelAddingActionPerformed

    private void addSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubmitActionPerformed
        
       int result =  JOptionPane.showConfirmDialog(rootPane,"Do you want to Approve All");
            if(result == JOptionPane.YES_OPTION){
        
        try{  //Creating Connection to Data Base
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    String url = "jdbc:oracle:thin:@//localhost:1521/XE";
                    String user = "system";
                   con = DriverManager.getConnection(url, user, "root");
                 String labId="lab1";
                  pst=con.prepareStatement("update ocacLab6 set computers=?,lights=?,chairs=?,ac=? where labid=?");
                   pst.setInt(1, newComputer);
                   pst.setInt(2, newLight);
                   pst.setInt(3, newChair);
                   pst.setInt(4, newAc);
                   pst.setString(5, labId);
                   pst.executeUpdate();
                   
                   JOptionPane.showMessageDialog(rootPane, "Data Updated Successfully");
                  aUp1.setVisible(false);
        aUp2.setVisible(false);
        aUp3.setVisible(false);
        aUp4.setVisible(false);
        addSubmit.setVisible(false);
        upLabel.setVisible(false);
        
        computerAdding.setText("0");
        lightAdding.setText("0");
        chairAdding.setText("0");
        acAdding.setText("0");
        cancelAdding.setVisible(false);
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, e);
                } 
            }
    }//GEN-LAST:event_addSubmitActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
         try{  //Creating Connection to Data Base
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    String url = "jdbc:oracle:thin:@//localhost:1521/XE";
                    String user = "system";
                   con = DriverManager.getConnection(url, user, "root");
                 String labId="lab1";
                  pst=con.prepareStatement("select computers,chairs,lights,ac from ocacLab6 where labid=?");
                    pst.setString(1,labId);
                   rs=pst.executeQuery();
                    while(rs.next()){
                        ctrGetData = String.valueOf(rs.getInt(1));
                        chiarGetData = String.valueOf(rs.getInt(2));
                        lightGetData =String.valueOf(rs.getInt(3));
                        acGetData=String.valueOf(rs.getInt(4));
                    }
                    computerView.setEditable(false);
                    chairView.setEditable(false);
                    lightView.setEditable(false);
                     acView.setEditable(false);
                   computerView.setText(ctrGetData);
                   chairView.setText(chiarGetData);
                   acView.setText(acGetData); 
                    lightView.setText(lightGetData);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, e);
                }
    }//GEN-LAST:event_refreshActionPerformed

    private void cancelRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRemoveActionPerformed
        
        
    }//GEN-LAST:event_cancelRemoveActionPerformed

    private void removeSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSubmitActionPerformed
       int result =  JOptionPane.showConfirmDialog(rootPane,"Do you want to Approve All");
            if(result == JOptionPane.YES_OPTION){
        
        try{  //Creating Connection to Data Base
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    String url = "jdbc:oracle:thin:@//localhost:1521/XE";
                    String user = "system";
                   con = DriverManager.getConnection(url, user, "root");
                 String labId="lab1";
                  pst=con.prepareStatement("update ocacLab6 set computers=?,lights=?,chairs=?,ac=? where labid=?");
                   pst.setInt(1, removenewComputer);
                   pst.setInt(2, removenewLight);
                   pst.setInt(3, removenewChair);
                   pst.setInt(4, removenewAc);
                   pst.setString(5, labId);
                   pst.executeUpdate();
                   
                   JOptionPane.showMessageDialog(rootPane, "Data Updated Successfully");
                  rUp1.setVisible(false);
        rUp2.setVisible(false);
        rUp3.setVisible(false);
        rUp4.setVisible(false);
        removeSubmit.setVisible(false);
        upLabel1.setVisible(false);
        
        computerRemove.setText("0");
        lightRemove.setText("0");
        chairRemove.setText("0");
        acRemove.setText("0");
        cancelRemove.setVisible(false);
                    
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, e);
                } 
            }
    }//GEN-LAST:event_removeSubmitActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
         ocacLab5 lb = new ocacLab5();
       lb.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_next1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ocacLab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ocacLab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ocacLab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ocacLab6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ocacLab6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aUp1;
    private javax.swing.JLabel aUp2;
    private javax.swing.JLabel aUp3;
    private javax.swing.JLabel aUp4;
    private javax.swing.JTextField acAdding;
    private javax.swing.JTextField acRemove;
    private javax.swing.JTextField acView;
    private javax.swing.JButton addSubmit;
    private javax.swing.JButton cancelAdding;
    private javax.swing.JButton cancelRemove;
    private javax.swing.JTextField chairAdding;
    private javax.swing.JTextField chairRemove;
    private javax.swing.JTextField chairView;
    private javax.swing.JTextField computerAdding;
    private javax.swing.JTextField computerRemove;
    private javax.swing.JTextField computerView;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane labTabPan;
    private javax.swing.JTextField lightAdding;
    private javax.swing.JTextField lightRemove;
    private javax.swing.JTextField lightView;
    private javax.swing.JButton next1;
    private javax.swing.JButton push2;
    private javax.swing.JLabel rUp1;
    private javax.swing.JLabel rUp2;
    private javax.swing.JLabel rUp3;
    private javax.swing.JLabel rUp4;
    private javax.swing.JButton refresh;
    private javax.swing.JButton removeSubmit;
    private javax.swing.JLabel upLabel;
    private javax.swing.JLabel upLabel1;
    // End of variables declaration//GEN-END:variables
}
